# On each Pull request against master branch,
# build documentation and check that the sphinx build works

name: OpenUpgradelib documentation

on:
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out OpenUpgrade Documentation
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check out Odoo
        uses: actions/checkout@v2
        with:
          repository: odoo/odoo
          ref: "16.0"
          fetch-depth: 1
          path: odoo
      - name: Configuration
        run: |
          sudo apt update
          sudo apt install \
              expect \
              expect-dev \
              libevent-dev \
              libldap2-dev \
              libsasl2-dev \
              libxml2-dev \
              libxslt1-dev \
              nodejs \
              python3-lxml \
              python3-passlib \
              python3-psycopg2 \
              python3-serial \
              python3-simplejson \
              python3-werkzeug \
              python3-yaml \
              unixodbc-dev
      - name: Requirements Installation
        run: |
          pip install -q -r odoo/requirements.txt
          pip install -e .
          pip install -r ./doc_requirements.txt

      - name: OpenUpgradelib Docs
        run: |
          # try to build the documentation
          python3 -m sphinx -W -d ./docs/.doctrees ./docsource ./docs
